### ISSUE TITLE
Magic Mouse scrolls two indexes 

### ISSUE THREAD

**Issue by nolafs** [joelmukuthu/angular-snapscroll#15]
Hi,

On a mac, it keeps jumping two indexes. I presume there is issue with inertia of scrolling on mac. Any idea how to fix this issue?

Cheers
Olaf

**Comment by joelmukuthu** [comment]
I suppose you found the note in the README :)
Yeah it's a known issue that affects all libraries that hijack the mousewheel/trackpad events on a Mac. Another hack is to reduce your trackpad's sensitivity and see that it does not snap twice. But of course you can't ask your users to do this hence the need to increase the animation duration

**Comment by nolafs** [comment]
Yeah, thanks for getting back me. Is working fine now. I just changed the easing to compensate for slower speed.

On 7 Mar 2016, at 11:06, Joel Mukuthu <notifications@github.com<mailto:notifications@github.com>> wrote:

I suppose you found the note in the README :)
Yeah it's a known issue that affects all libraries that hijack the mousewheel/trackpad events on a Mac. Another hack is to reduce your trackpad's sensitivity and see that it does not snap twice. But of course you can't ask your users to do this hence the need to increase the animation duration

**Comment by joelmukuthu** [comment]
No worries, glad you got it working
