### ISSUE TITLE
Chrome snap issue

### ISSUE THREAD

**Issue by nolafs** [joelmukuthu/angular-snapscroll#16]
Hi,

I am having issues with chrome on Mac. It keeps jumping to previous scroll snap. Any ideas what this could cause this?

Cheers
Olaf

**Comment by joelmukuthu** [comment]
Hi Olaf,

Do you have the page online where I can see the bug or some code that
reproduces it?

**Comment by nolafs** [comment]
Hi Joel,

Not at the moment but the issue occurs on demo page.

I will see if I can get demo up on our dev server.

Cheers
Olaf

Sent from my iPhone

On 8 Mar 2016, at 21:19, Joel Mukuthu <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Olaf,

Do you have the page online where I can see the bug or some code that
reproduces it?
On 8 Mar 2016 18:47, "nolafs" <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hi,
> 
> I am having issues with chrome on Mac. It keeps jumping to previous scroll
> snap. Any ideas what this could cause this?
> 
> Cheers
> Olaf
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/joelmukuthu/angular-snapscroll/issues/16.

##

**Comment by joelmukuthu** [comment]
Oh, that's interesting. I don't have a Mac to test with but I can check it
out tomorrow at work. What browser/mac version is it? And did it happen
while using the trackpad?

On 8 March 2016 at 22:23, nolafs notifications@github.com wrote:

> Hi Joel,
> 
> Not at the moment but the issue occurs on demo page.
> 
> I will see if I can get demo up on our dev server.
> 
> Cheers
> Olaf
> 
> Sent from my iPhone
> 
> On 8 Mar 2016, at 21:19, Joel Mukuthu <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> Hi Olaf,
> 
> Do you have the page online where I can see the bug or some code that
> reproduces it?
> On 8 Mar 2016 18:47, "nolafs" <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> > Hi,
> > 
> > I am having issues with chrome on Mac. It keeps jumping to previous
> > scroll
> > snap. Any ideas what this could cause this?
> > 
> > Cheers
> > Olaf
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/joelmukuthu/angular-snapscroll/issues/16.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193972496
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193973641
> .

## 

Joel Mukuthu.

**Comment by nolafs** [comment]
Is latest chrome version. Safari is all good. I haven't checked with trackpad, only with a Magic Mouse.

Sent from my iPhone

On 8 Mar 2016, at 21:30, Joel Mukuthu <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh, that's interesting. I don't have a Mac to test with but I can check it
out tomorrow at work. What browser/mac version is it? And did it happen
while using the trackpad?

On 8 March 2016 at 22:23, nolafs <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hi Joel,
> 
> Not at the moment but the issue occurs on demo page.
> 
> I will see if I can get demo up on our dev server.
> 
> Cheers
> Olaf
> 
> Sent from my iPhone
> 
> On 8 Mar 2016, at 21:19, Joel Mukuthu <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
> 
> Hi Olaf,
> 
> Do you have the page online where I can see the bug or some code that
> reproduces it?
> On 8 Mar 2016 18:47, "nolafs" <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
> 
> > Hi,
> > 
> > I am having issues with chrome on Mac. It keeps jumping to previous
> > scroll
> > snap. Any ideas what this could cause this?
> > 
> > Cheers
> > Olaf
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/joelmukuthu/angular-snapscroll/issues/16.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193972496
> 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193973641
> .

## 

Joel Mukuthu.

##

**Comment by joelmukuthu** [comment]
Okay, I'll try to reproduce it and get back to you :)

On 8 March 2016 at 22:32, nolafs notifications@github.com wrote:

> Is latest chrome version. Safari is all good. I haven't checked with
> trackpad, only with a Magic Mouse.
> 
> Sent from my iPhone
> 
> On 8 Mar 2016, at 21:30, Joel Mukuthu <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> Oh, that's interesting. I don't have a Mac to test with but I can check it
> out tomorrow at work. What browser/mac version is it? And did it happen
> while using the trackpad?
> 
> On 8 March 2016 at 22:23, nolafs <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> > Hi Joel,
> > 
> > Not at the moment but the issue occurs on demo page.
> > 
> > I will see if I can get demo up on our dev server.
> > 
> > Cheers
> > Olaf
> > 
> > Sent from my iPhone
> > 
> > On 8 Mar 2016, at 21:19, Joel Mukuthu <notifications@github.com<mailto:
> > notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> > 
> > Hi Olaf,
> > 
> > Do you have the page online where I can see the bug or some code that
> > reproduces it?
> > On 8 Mar 2016 18:47, "nolafs" <notifications@github.com<mailto:
> > notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> > 
> > > Hi,
> > > 
> > > I am having issues with chrome on Mac. It keeps jumping to previous
> > > scroll
> > > snap. Any ideas what this could cause this?
> > > 
> > > Cheers
> > > Olaf
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/joelmukuthu/angular-snapscroll/issues/16.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193972496
> > 
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193973641
> > 
> > .
> 
> ## 
> 
> Joel Mukuthu.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193976777
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-193977714
> .

## 

Joel Mukuthu.

**Comment by pitakill** [comment]
Yes, I can confirm this in Chrome Version 49.0.2623.87 (64-bit) in Mac OS X 10.11.4

Do you have some advice to fix this? :)

**Comment by joelmukuthu** [comment]
Hi!

I haven't confirmed this but I think it's caused by the fact that this
module hijacks the browser/system's scroll events, infers the scroll
direction then animates in that direction. Determining the scroll direction
shouldn't be affected by your mac's mouse/trackpad settings but perhaps
something changed. Theories aside, do you experience the same issue with
this jQuery plugin http://projects.lukehaas.me/scrollify?

And sorry Olaf for not getting back to you.. I'm on holiday and didn't get
a chance to look at this before I went on holiday.

Joel

**Comment by nolafs** [comment]
Hi Joel,

Thanks and no problem regarding the delay. I will try the jquery version and let you know.

I will have look myself but you might be right. The animation to the next section does complete but it seems it does not detect or increases the index. This causes it to jump back.

Cheers
Olaf

Sent from my iPhone

On 29 Mar 2016, at 08:54, Joel Mukuthu <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi!

I haven't confirmed this but I think it's caused by the fact that this
module hijacks the browser/system's scroll events, infers the scroll
direction then animates in that direction. Determining the scroll direction
shouldn't be affected by your mac's mouse/trackpad settings but perhaps
something changed. Theories aside, do you experience the same issue with
this jQuery plugin http://projects.lukehaas.me/scrollify?

And sorry Olaf for not getting back to you.. I'm on holiday and didn't get
a chance to look at this before I went on holiday.

Joel
On 29 Mar 2016 01:45, "Leopoldo Caballero" <notifications@github.com<mailto:notifications@github.com>> wrote:

> Yes, I can confirm this in Chrome Version 49.0.2623.87 (64-bit) in Mac OS
> X 10.11.4
> 
> Do you have some advice to fix this? :)
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joelmukuthu/angular-snapscroll/issues/16#issuecomment-202612755

##

**Comment by nolafs** [comment]
Hi Joel,

The Scrolify works, no issue at all.

Cheers
Olaf

On 29 Mar 2016, at 08:53, Joel Mukuthu <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi!

I haven't confirmed this but I think it's caused by the fact that this
module hijacks the browser/system's scroll events, infers the scroll
direction then animates in that direction. Determining the scroll direction
shouldn't be affected by your mac's mouse/trackpad settings but perhaps
something changed. Theories aside, do you experience the same issue with
this jQuery plugin http://projects.lukehaas.me/scrollify?

And sorry Olaf for not getting back to you.. I'm on holiday and didn't get
a chance to look at this before I went on holiday.

Joel

**Comment by nolafs** [comment]
Hi Joel,

I found a way to fix it. Bit of a hack but it works. Basically the delta hits -0 which than causes the snapindex to change. Simple adding on line 192 

if(delta===0){
        return;
      }

will fix it in chrome.

Cheers
Olaf

**Comment by joelmukuthu** [comment]
Hi Olaf,

Thank you so much for the fix! I'll reproduce that in a unit test and add
the fix. But if you have the time feel free to creare a PR :)

Joel
