### ISSUE TITLE
Click on links does not work

### ISSUE THREAD

**Issue by pitakill** [joelmukuthu/angular-snapscroll#17]
In the demo page when I enter with a mobile device (Android or Apple), I can't follow the links; the only thing i can do is to swipe down or up.

Do you see this behavior?

**Comment by pitakill** [comment]
Accordingly with the project (angular-swipe):

https://github.com/marmorkuchen-net/angular-swipe

is a known issue, so there is a workaround (adding a class in the markup)

**Comment by joelmukuthu** [comment]
Thanks Leopoldo :)
