### ISSUE TITLE
Routing; go to URL snapIndex (location hash) only works if it is a new tab

### ISSUE THREAD

**Issue by MikelArnaiz** [joelmukuthu/angular-snapscroll#19]
If you go to https://joelmukuthu.github.io/angular-snapscroll/#3 you will see 4th 'view', that's fine.
Change now URL hash to 1, nothing happens. It only works if it is a new window/tab.

**Comment by joelmukuthu** [comment]
Hi Mikel,
That is out of the scope of this project, but you could use a `setInterval` to continously poll the current hash and update `snapIndex` if the hash changes. I'll update the demo when I get a chance
