### ISSUE TITLE
Wheel Event not working correctly

### ISSUE THREAD

**Issue by Muenze** [joelmukuthu/angular-snapscroll#2]
Hi,

I´m testing your library for my Code and noticed that the wheel event isn't working correctly.
The code in the onWheel Function isn't working, you are trying to get properties from e, but in Safari, FF and Chrome these properties are nestes in e.originalEvent.

**Comment by joelmukuthu** [comment]
Hey, thanks for pointing this out. I suppose you're also using jquery in your project, since this is the case where the event returned by jqLite's `on` method is not the original browser event. At least I was able to reproduce this issue by including jquery in a sample app.

Thanks for the PR!

**Comment by joelmukuthu** [comment]
fyi I added a [test case](https://github.com/joelmukuthu/angular-snapscroll/commit/84e06f9d93e574099f6854b8d231f1d7cd89853d) for this and released a new version
