### ISSUE TITLE
Disable programmatically

### ISSUE THREAD

**Issue by bpalermo** [joelmukuthu/angular-snapscroll#20]
It's possible to disable programmatically, in case of screen resize?

**Comment by joelmukuthu** [comment]
Hi. I don't quite understand your question, you don't want it to resize the items when the window is resized?

**Comment by bpalermo** [comment]
Not actually, when I have a small screen, iPhone 5S, it doesn't re-size correctly, I can't get to the last slide for example. So I would like to disable and let the user scroll freely.

**Comment by joelmukuthu** [comment]
Hmm, I hadn't considered that. A proper solution for this should be available when I get around to finishing https://github.com/joelmukuthu/angular-snapscroll/issues/12. However, for the time being you can prevent sending the swipe events to snapscroll and then disable the scroll listener using the [prevent-snapping-after-manual-scroll](https://github.com/joelmukuthu/angular-snapscroll/blob/6b211d5dd421c6f6a94ef962166d5def2d2153b3/DOCS.md#prevent-snapping-after-manual-scroll) attribute. Something like this:

``` html
<div snapscroll prevent-snapping-after-manual-scroll 
    snap-index="snapIndex" ng-swipe-up="swipeUp()" ng-swipe="swipeDown()">
    <div></div>
    <div></div>
    <div></div>
</div>
```

``` js
app.controller('MainController', ['$scope', '$window', function ($scope, $window) {
  $scope.swipeUp = function () {
    if ($window.innerWidth > 320) {
      $scope.snapIndex++;
    }
  };
  $scope.swipeDown = function () {
    if ($window.innerWidth > 320) {
      $scope.snapIndex--;
    }
  };
}]);
```

EDIT: This has the undesirable side effect that it also prevents the scroll listener for all browsers..
