### ISSUE TITLE
Dynamically added children do not show up at all on mobile device

### ISSUE THREAD

**Issue by suymilk** [joelmukuthu/angular-snapscroll#21]
When using ng-repeat, slides do not show up at all on my iPhone 6 (latest software). It works fine in my Chrome's mobile device emulator, which strikes me as even stranger. When accessing the demo site from my phone, the "dynamically added children" section also has the same problem (only slide 1 shows up; there are no other slides I can scroll to).

**Comment by suymilk** [comment]
Never mind -- was an issue with the way that the data was being loaded!

**Comment by joelmukuthu** [comment]
Hi. I'm glad you got it to work :). Do you have issues with the demo site on your phone though?
