### ISSUE TITLE
Support child elements with height greater than snapscroll element height

### ISSUE THREAD

**Issue by m0ngr31** [joelmukuthu/angular-snapscroll#26]
I have an ng-repeat where the elements are all columns that are horizontal, and if there are too many to fit on the screen, it'll overflow to a new row (but not a new div). Is there a way to make the snapscroll directive automatically handle this situation and just scroll to the next row?

**Comment by joelmukuthu** [comment]
Not with the current structure I'm afraid. You'd have to use javascript to figure out how many elements will fit on the current width and to put the overflowing ones in new divs

**Comment by joelmukuthu** [comment]
In #25 I'm working on fixing this i.e. making snapscroll work with varying children heights. It's currently working with children whose height is smaller than the snapscroll element but not with children whose height is greater, I'll have to work on that next
