### ISSUE TITLE
horizontal scrolling

### ISSUE THREAD

**Issue by edparsons** [joelmukuthu/angular-snapscroll#34]
Would it be difficult to add a feature for nest scrolling to go horizontally, rather than just vertically?

**Comment by joelmukuthu** [comment]
we could add an attribute as a flag that ends up setting `scrollLeft` instead of `scrollTop` here https://github.com/joelmukuthu/angular-snapscroll/blob/v0.3.1/src/services/scroll.js#L29. but how would you expect the mousewheel to work in this case?
