### ISSUE TITLE
Nested native scroll ignored

### ISSUE THREAD

**Issue by jernejc** [joelmukuthu/angular-snapscroll#37]
Hi, thanks for the nice little plugin.

I'm experiencing a weird issue, where I have a nested element which is scrollable horizontally, but as soon as I enable the snap-scroll directive that scrolling triggers the snapTo animation instead of the scroll event on that element. 

I tried stopping propagation of the scroll event and all swipe events on that element, but none of them seemed to trigger.

Here is an example:
https://run.plnkr.co/FzfAfOrHjj8x5hHk/

Can edit here:
https://plnkr.co/edit/JE5tbWXtWCIqqzWG2EIO?p=preview

Those images are horizontally scrollable until you enable the plugin, try removing the directive, to see how they're suppose to behave. Any idea how can I stop the event propagating?

Thanks
Jernej

**Comment by joelmukuthu** [comment]
Hi Jernej. Thanks for reporting this, it's apparent that angular-wheelie does not differentiate between left/right and up/down mousewheel events. I'll work on a fix!

**Comment by jernejc** [comment]
Great, thanks

**Comment by joelmukuthu** [comment]
Fix is out with v1.0.1

**Comment by jernejc** [comment]
Thanks, will give it a go
