### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by mac-r** [joelmukuthu/angular-snapscroll#4]
The way you designed is great. Super easy to customize and make it work properly. I am surprised it has so few stars

**Comment by joelmukuthu** [comment]
thanks, i'm glad it's working for you :)

**Comment by mac-r** [comment]
@joelmukuthu i just discovered that it's super slow in safari and mozilla... do you know how to fix it?

**Comment by joelmukuthu** [comment]
Hi, sorry for the slow response. Do you mean that the animation is janky or that it takes too long? If the site you're working on is online could you please link me to it? (you can send me a direct email for that :)
