### ISSUE TITLE
Add support for CommonJS

### ISSUE THREAD

**Issue by slavafomin** [joelmukuthu/angular-snapscroll#46]
Hello!

Thank you for this great library!

However, please add support for CommonJS. This will allow this library to be used with e.g. webpack.

Consider this example: https://github.com/betsol/angular-input-modified/blob/master/index.js.

Thanks!

**Comment by joelmukuthu** [comment]
Oh for sure!

**Comment by joelmukuthu** [comment]
Fixed in 1.3.0
