### ISSUE TITLE
How to use scroll.To method

### ISSUE THREAD

**Issue by santteegt** [joelmukuthu/angular-snapscroll#5]
hi,

could you please give me an example of how to use the scroll.to method? I don't know how to access snapscroll methods inside an angular controller.

Thanks in advance.

**Comment by joelmukuthu** [comment]
Hi. How are you trying to use it? If what you want is to be able to control the snapping using code you would use the snap-index attribute not the scroll service. For example:
HTML:

``` html
<div snapscroll="" snap-index="index"></div>
```

Controller:

``` javascript
app.controller('MainCtrl', ['$scope', function ($scope) {
    $scope.index = 1; // will cause the snapscroll instance to go to index 1, or snap upwards
    $scope.index = 0; // will cause the snapscroll instance to go to index 0, or snap downwards
}]);
```

For more usage example view the source on the [demo](http://joelmukuthu.github.io/angular-snapscroll).

If you really want to be using the scroll service then you just inject it into your controller:

``` javascript
app.controller('MainCtrl', ['scroll', function (scroll) {
    var element = angular.element('#some-element');
    scroll.to(element, 100, 400);
}]);
```

For more on how to use that service, have a look at the [docs](https://github.com/joelmukuthu/angular-snapscroll/blob/master/DOCS.md#scrolltoelement-top-duration-easing).
