### ISSUE TITLE
The scroll does not go to the index when using ng-click="snapIndex=$index" with ngRepeat.

### ISSUE THREAD

**Issue by komushi** [joelmukuthu/angular-snapscroll#8]
I added a breakpoint at scope.$watch('snapIndex') but it did not trigger the breakpoint when using ng-click="snapIndex=$index". However hard-coded snapIndex=1 works. What have I done wrong?

My code is like below:

```
    <div class="panel panel-transparent">
        <div class="row">
            <div class="col-lg-1 col-md-1 ">
                <ul class="nav nav-tabs nav-tabs-simple nav-tabs-left bg-white" id="tab-3">
                    <li ng-repeat="image in images" ng-class="{active: snapIndex == $index}">
                        <a ng-click="snapIndex=$index" pg-tab href="#">{{$index}}</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-11 col-md11">
                <div class="tab-content bg-white" snapscroll="" fit-window-height="90%" snap-index="snapIndex" snap-duration="1200">
                    <image-container ng-repeat="image in images">
                        <img src="{{image.imageUrl}}"></img>
                    </image-container>
                </div>
            </div>
        </div>
    </div>
```

Thanks!

**Comment by joelmukuthu** [comment]
Hi!

It's because ng-repeat creates it's own scope, so it's not setting snapIndex on the parent scope. This should fix it:

``` html
<a ng-click="$parent.snapIndex=$index" pg-tab href="#">{{$index}}</a>
```

Btw I very much like what you did here: `fit-window-height="90%"`. Do you mind if I add that feature into the main code base? I'm assuming it makes the snapscroll's height equal to 90% of the window height, is that right?

**Comment by komushi** [comment]
Thanks for the quick response.

And fit-window-height is a good feature and I really prefer to have a parameter for it.
I have a header and a footer so I need the height of the image to be programmatically adjusted.

Thanks.

**Comment by joelmukuthu** [comment]
No problem. I'll close this issue and create a new issue for having a parameter for `fit-window-height`.
